"""
Handles console output and rich UI formatting for the GlitchLab controller.
Public API includes functions for rendering status, errors, and agent progress.
Fits into the controller decomposition by abstracting all display logic away from core execution.
"""

from __future__ import annotations

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from glitchlab.task import Task

console = Console()


def print_plan(plan: dict) -> None:
    """Print the execution plan as a Rich table."""
    table = Table(title="Execution Plan", border_style="magenta")
    table.add_column("#", style="dim")
    table.add_column("Action")
    table.add_column("Files")
    table.add_column("Description")

    for step in plan.get("steps", []):
        table.add_row(
            str(step.get("step_number", "?")),
            step.get("action", "?"),
            ", ".join(step.get("files", [])),
            step.get("description", ""),
        )

    console.print(table)
    console.print(
        f"Risk: [bold]{plan.get('risk_level', '?')}[/] | "
        f"Core change: {plan.get('requires_core_change', False)} | "
        f"Complexity: {plan.get('estimated_complexity', '?')}"
    )


def print_security_issues(sec: dict) -> None:
    """Print security issues with severity-colored output."""
    for issue in sec.get("issues", []):
        sev = issue.get("severity", "info")
        color = {"critical": "red", "high": "red", "medium": "yellow"}.get(sev, "dim")
        console.print(f"  [{color}]{sev.upper()}[/] {issue.get('description', '')}")


def print_budget_summary(budget_summary: dict) -> None:
    """Print token/cost budget summary panel."""
    console.print(Panel(
        f"Tokens: {budget_summary['total_tokens']:,} / "
        f"Cost: ${budget_summary['estimated_cost']:.4f} / "
        f"Calls: {budget_summary['call_count']}",
        title="💸 Budget",
        border_style="green",
    ))
    if budget_summary.get("role_usage"):
        for role, tokens in sorted(budget_summary["role_usage"].items()):
            console.print(f"  [dim]{role}: {tokens:,} tokens[/]")


def build_pr_body(task: Task, impl: dict, release: dict) -> str:
    """Build the PR body markdown."""
    body = f"""## 🔬 GLITCHLAB Automated PR

**Task:** {task.task_id}
**Source:** {task.source}

### Summary
{impl.get('summary', 'No summary provided.')}

### Changes
"""
    for change in impl.get("changes", []):
        body += (
            f"- `{change.get('action', '?')}` "
            f"{change.get('file', '?')}: "
            f"{change.get('description', '')}\n"
        )

    body += f"""
### Version Impact
- **Bump:** {release.get('version_bump', 'unknown')}
- **Reasoning:** {release.get('reasoning', 'N/A')}

### Changelog
{release.get('changelog_entry', 'N/A')}

---
*Generated by GLITCHLAB — Build Weird. Ship Clean.*
"""
    return body
