import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from loguru import logger


def insert_doc_comments(file_path: Path, router: Any) -> bool:
    """
    Surgically insert /// doc comments above public functions that lack one.
    Asks the model only for comment text, does file manipulation in Python.
    """
    lines = file_path.read_text().splitlines()
    functions_needing_docs = []

    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("pub fn ") or stripped.startswith("pub async fn "):
            j = i - 1
            while j >= 0 and lines[j].strip() == "":
                j -= 1
            if j < 0 or not lines[j].strip().startswith("///"):
                functions_needing_docs.append((i, line))

    if not functions_needing_docs:
        logger.info("[DOC] No public functions missing doc comments.")
        return False

    fn_list = "\n".join(
        f"Line {i+1}: {line.strip()}" for i, line in functions_needing_docs
    )
    prompt = f"""For each of the following Rust public functions, write a single concise /// doc comment (one line only).
Return a JSON array where each item has "line" (the line number) and "comment" (the full /// comment string).
Example: [{{"line": 42, "comment": "/// Initializes the vault and loads existing keys."}}]

Functions:
{fn_list}
"""
    response = router.complete(
        role="implementer",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=2048,
    )

    content = response.content.strip()
    if content.startswith("```"):
        content = "\n".join(
            line for line in content.split("\n") if not line.strip().startswith("```")
        )

    try:
        comments = json.loads(content)
    except json.JSONDecodeError:
        match = re.search(r"\[.*\]", content, re.DOTALL)
        if match:
            try:
                comments = json.loads(match.group())
            except json.JSONDecodeError:
                logger.error("[DOC] Failed to parse doc comments from model response")
                return False
        else:
            logger.error("[DOC] Failed to parse doc comments from model response")
            return False

    comment_map = {item["line"]: item["comment"] for item in comments}

    for i, line in reversed(functions_needing_docs):
        line_num = i + 1
        comment = comment_map.get(line_num)
        if comment:
            indent = len(line) - len(line.lstrip())
            comment_text = comment.strip()
            if not comment_text.startswith("///"):
                comment_text = "/// " + comment_text
            comment_line = " " * indent + comment_text
            lines.insert(i, comment_line)

    file_path.write_text("\n".join(lines) + "\n")
    logger.info(f"[DOC] Inserted {len(comment_map)} doc comments into {file_path.name}")
    return True


def write_adr(ws_path: Path, adr: dict | str) -> str | None:
    """Write an ADR to the workspace."""
    adr_dir = ws_path / ".context" / "decisions"
    if not adr_dir.exists():
        adr_dir = ws_path / "docs" / "adr"
    adr_dir.mkdir(parents=True, exist_ok=True)

    existing = list(adr_dir.glob("*.md"))
    next_num = len(existing) + 1

    # Handle the case where the LLM returns a raw markdown string
    if isinstance(adr, str):
        title = f"ADR-{next_num:03d}"
        # Try to extract a title from the first markdown header
        first_line = adr.strip().split('\n')[0]
        if first_line.startswith('# '):
            title = first_line.replace('# ', '').strip()

        safe_title = re.sub(r'[^a-z0-9\-]+', '-', title.lower())
        safe_title = re.sub(r'-+', '-', safe_title).strip('-')
        filename = f"{next_num:03d}-{safe_title[:50]}.md"
        filepath = adr_dir / filename

        filepath.write_text(adr + "\n\n---\n*Generated by GLITCHLAB / Archivist Nova*\n")
        return f"ADR {filepath.relative_to(ws_path)}"

    # Handle the case where the LLM returns a structured dictionary
    title = adr.get("title", f"ADR-{next_num:03d}")
    safe_title = re.sub(r'[^a-z0-9\-]+', '-', title.lower())
    safe_title = re.sub(r'-+', '-', safe_title).strip('-')
    filename = f"{next_num:03d}-{safe_title[:50]}.md"
    filepath = adr_dir / filename

    content = f"""# {title}

**Status:** {adr.get('status', 'accepted')}
**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d')}

## Context

{adr.get('context', 'N/A')}

## Decision

{adr.get('decision', 'N/A')}

## Consequences

{adr.get('consequences', 'N/A')}
"""
    alternatives = adr.get("alternatives_considered", [])
    if alternatives:
        content += "\n## Alternatives Considered\n\n"
        for alt in alternatives:
            content += f"- {alt}\n"

    content += "\n---\n*Generated by GLITCHLAB / Archivist Nova*\n"

    filepath.write_text(content)
    return f"ADR {filepath.relative_to(ws_path)}"


def write_doc_update(ws_path: Path, doc: dict) -> str | None:
    """Apply a documentation update."""
    fpath = ws_path / doc["file"]
    action = doc.get("action", "create")
    content = doc.get("content", "")

    if not content:
        return None

    if action == "create":
        fpath.parent.mkdir(parents=True, exist_ok=True)
        fpath.write_text(content)
        return f"DOC CREATE {doc['file']}"
    elif action == "append":
        fpath.parent.mkdir(parents=True, exist_ok=True)
        existing = fpath.read_text() if fpath.exists() else ""
        fpath.write_text(existing + "\n\n" + content)
        return f"DOC APPEND {doc['file']}"
    elif action == "update" and fpath.exists():
        fpath.write_text(content)
        return f"DOC UPDATE {doc['file']}"
    return None
